@url = http://127.0.0.1:3000/
//@url = https://allons-y.herokuapp.com/

//Resources
@post = posts
@identity = identities
@user = users


###
POST {{url}}login
Content-Type: application/json

{
	"payload" : {
		"type" : "social",
		"social" : {
			"provider" : "google",
			"id" : "4347389478745"
		},
		"name" : "Kishan Kumar",
		"email" : "kumar.kishasn@outlook.com"
	}
}



###
GET {{url}}{{post}}/mock?count=10000


###
GET {{url}}{{user}}/mock?count=20
###
GET {{url}}{{post}}?skip=12&count=23

###
GET {{url}}{{post}}/count


###
GET {{url}}{{identity}}

###
POST {{url}}identities
Content-Type: application/json

{
	"payload" : {
		"deviceName" : "ACER R5-471T"
	}
}

###
POST {{url}}{{identity}}/query
Content-Type: application/json

{
	"query" : {
		"uniqueIdentifier" : {
			"$regex" : "345",
			"$options" : "mi"
		}
	}
}

###

